---
- name: Test my server
  hosts: all
  become: true

  tasks:
  - name: ping my servers
    ping:
 
  - name: Reboot the server
    shell: "sleep 5 && reboot"
    async: 1
    poll: 0

  - name: Wait for the reboot to complete if there was a change.
    wait_for:
      port: 22
      host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
      search_regex: OpenSSH
      delay: 10
      timeout: 60
    connection: local

  - block:
     - name: Install service on Ubuntu
       apt: name={{item}} state=latest
       with_items:
         - apache2
         - ssh
         - python3-pip
         - mc
         - vim
         - net-tools
         - curl
         - zip
         - git
         - wget

    when: ansible_os_family == "Debian"
  
  - block:
     - name: Install service on Centos
       yum: name={{item}} state=latest
       with_items:
         - httpd
         - mc
         - vim
         - net-tools
         - curl
         - zip
         - git
         - wget
 
    when: ansible_os_family == "RedHat"  
 
