---
- name: Ansible hosts
  hosts: linux2
  become: yes

  tasks:
  - name: Create user
    user: 
      name: test2
      groups: sudo
      password: $6$fKr310y.hZYLD$og.MMgYP9EI.Q90xT4FFHzXCiyUaHbOV7f62mYpwrjrpUwgbuaVC2Sx1QvjJ4R8HvOaIpwv6zaRuAujtl72tU.
  - name: Add SSH
    authorized_key: 
       user=test2 
       state=present
       key={{ item }}
    with_file:
        - /home/vagrant/.ssh/id_rsa.pub
